### ISSUE TITLE
white text 1.10.2

### ISSUE THREAD

**Issue by m1jordanallen** [wyldmods/SimpleAchievements#10]
Hello, I have been using your mod, but I have noticed that a lot of white text while using it in 1.10.2.

Ive tried a few forge versions as well as played with as many configs as I can.  Turning on shadows seems to allow the text to show, but is hard to read.  To be clear, the text is there, it is just white.

Here is a pic with text in the description:
http://imgur.com/a/tKcsB

**Comment by tterrag1098** [comment]
Fixed and published here https://minecraft.curseforge.com/projects/simple-achievements/files/2325240
