### ISSUE TITLE
Achievement Book and JEI Interaction Bug 

### ISSUE THREAD

**Issue by Darkosto** [wyldmods/SimpleAchievements#12]
When the achievement book is opened and the bottom right "next page" button is positioned where an item from JEI is displayed clicking the next button opens the recipe window from JEI. Visually the simple achievement book is on top, but functionally the JEI items are covering it.

SA Version: 1.2.2-26
Forge: 2185
JEI Version: 3.13.6.393

**Comment by tterrag1098** [comment]
Fixed via https://github.com/mezz/JustEnoughItems/commit/97507b22b4aaf32057c26edc16c29401a02f2a05

**Comment by Darkosto** [comment]
Thanks for following up on this Tterrag :)
