### ISSUE TITLE
When rebinding inventory key, pressing next page opens NEI instead

### ISSUE THREAD

**Issue by Sekra** [wyldmods/SimpleAchievements#14]
I just started playing Skyfactory 3 pack and as usual since always I rebind my inventory key to the TAB key instead of the normal e key. Now whenever I read the achievement book and press the next page it will open up NEI instead of showing the next page. I do not know if its an NEI or SA bug, but I figured I'd report it here.

**Comment by tterrag1098** [comment]
Fixed in JEI see #12
