### ISSUE TITLE
Game crash/No achievements found SP

### ISSUE THREAD

**Issue by Infernadoo** [wyldmods/SimpleAchievements#25]
I'm playing the Divine Journey modpack, 1.7.10, everything was working fine, but one day when I tried to load my SP world, the game just crashed and said: "The game crashed whilst exception in server tick loop Error: java.lang.NullPointerException: Exception in server tick loop" Does that every single time I try to load my world.
When I tried to load up a backup I can get into the game, but when I try to open to achievement book it says "No achievements found - check file encoding", when I try to copy the file from the original world or copy the text, it resets and does the same thing again, when I set it to read-only, it crashes once again and says: "The game crashed whilst ticking entity
Error: java.lang.ArrayIndexOutOfBoundsException: 0", then resets the file.
I can send crash reports if you need them.

**Comment by Infernadoo** [comment]
[crash-2018-02-22_19.34.08-server.txt](https://github.com/wyldmods/SimpleAchievements/files/1753247/crash-2018-02-22_19.34.08-server.txt)
[crash-2018-02-22_19.43.29-server.txt](https://github.com/wyldmods/SimpleAchievements/files/1753248/crash-2018-02-22_19.43.29-server.txt)
[crash-2018-02-23_14.21.53-server.txt](https://github.com/wyldmods/SimpleAchievements/files/1753249/crash-2018-02-23_14.21.53-server.txt)
[crash-2018-02-23_14.34.58-server.txt](https://github.com/wyldmods/SimpleAchievements/files/1753250/crash-2018-02-23_14.34.58-server.txt)
[crash-2018-02-23_22.28.20-server.txt](https://github.com/wyldmods/SimpleAchievements/files/1753251/crash-2018-02-23_22.28.20-server.txt)
[crash-2018-02-23_22.40.37-server.txt](https://github.com/wyldmods/SimpleAchievements/files/1753252/crash-2018-02-23_22.40.37-server.txt)
[crash-2018-02-23_22.40.56-client.txt](https://github.com/wyldmods/SimpleAchievements/files/1753253/crash-2018-02-23_22.40.56-client.txt)
[crash-2018-02-22_18.55.09-server.txt](https://github.com/wyldmods/SimpleAchievements/files/1753254/crash-2018-02-22_18.55.09-server.txt)
[crash-2018-02-22_19.07.46-server.txt](https://github.com/wyldmods/SimpleAchievements/files/1753255/crash-2018-02-22_19.07.46-server.txt)
[crash-2018-02-22_19.17.48-server.txt](https://github.com/wyldmods/SimpleAchievements/files/1753256/crash-2018-02-22_19.17.48-server.txt)
[crash-2018-02-22_19.27.33-server.txt](https://github.com/wyldmods/SimpleAchievements/files/1753257/crash-2018-02-22_19.27.33-server.txt)

**Comment by tterrag1098** [comment]
These errors are coming from BetterQuesting, not SA.
