### ISSUE TITLE
Having a crash in SMP

### ISSUE THREAD

**Issue by Tsunayoshi** [wyldmods/SimpleAchievements#3]
I have a crash in SMP, SSP works fine with same config.
It happens when opening the SA-Book.

The server conole gives me this error message: http://pastebin.com/reimYHDL
This is the client crash-report: http://pastebin.com/81S7VWBH

Here are the config files from config\SimpleAchievements:
http://pastebin.com/mWQQskcV
http://pastebin.com/G219nAPf

And here are the generated world files from world/SimpleAchievements:
SMP:
{
  "Schubychan": {
    "elements": []
  }
}

SSP:
http://pastebin.com/r15gMdhn

**Comment by Tsunayoshi** [comment]
I have removed all ä ü ö and ,
now it works

**Comment by tterrag1098** [comment]
This is bizzare, using special characters should not cause this. That could only happen if the list of pages is empty.

**Comment by tterrag1098** [comment]
I copied over your configs to my instance, and while I don't crash, the special characters are all kinds of messed up.

![](http://puu.sh/hkSyS.png)

Though I think this may be an encoding issue.

**Comment by tterrag1098** [comment]
Ok currently the reader uses your system's default encoding setting, which in this case appears to be UTF-8, but I think you are saving the file in ANSI (ASCII) encoding so it fails to read any data. If you encode the text file into UTF-8 It should work fine...

**Comment by Tsunayoshi** [comment]
Oh my gosh, yeah your completely right with this. My files are saved as ANSI -.-
And all works, included the special chars!!
Thank you for your help! THIS is really cool :)

**Comment by tterrag1098** [comment]
NP. The next release will have some safeguards around empty books, so it
doesn't just crash.
