### ISSUE TITLE
Anyone know how to use the mod?

### ISSUE THREAD

**Issue by PalePyth** [wyldmods/SimpleAchievements#8]
I found no description about how to work with the mod.
I downloaded the Sky Factory 2 server and found the configs of the simple achievements. It makes no sense. I can't set any custom achievements.
SOMEONE, HELP ME TO GET HOW TO WORK WITH THE MOD!
achievementList.txt: http://pastebin.com/1J8U4hfN

**Comment by tterrag1098** [comment]
Could you post what you've tried? You just gave me the file from SkyFactory.

**Comment by PalePyth** [comment]
I don't get how to add an achievement.

**Comment by tterrag1098** [comment]
You just add a line into achievementList.txt

**Comment by PalePyth** [comment]
Could you give an example? For example, I want to have an achievement after eating a carrot.

**Comment by tterrag1098** [comment]
This mod doesn't add triggered achievements. It's just a checklist.
